# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ants_admin 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "ants_admin"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["KarlNguyen"]
  s.date = "2014-09-11"
  s.description = "Admin panel for you"
  s.email = "thanhkhoait@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "ants_admin.gemspec",
    "app/assets/images/ants_admin/jquery_ui/animated-overlay.gif",
    "app/assets/images/ants_admin/jquery_ui/ui-bg_diagonals-thick_18_b81900_40x40.png",
    "app/assets/images/ants_admin/jquery_ui/ui-bg_diagonals-thick_20_666666_40x40.png",
    "app/assets/images/ants_admin/jquery_ui/ui-bg_flat_10_000000_40x100.png",
    "app/assets/images/ants_admin/jquery_ui/ui-bg_glass_100_f6f6f6_1x400.png",
    "app/assets/images/ants_admin/jquery_ui/ui-bg_glass_100_fdf5ce_1x400.png",
    "app/assets/images/ants_admin/jquery_ui/ui-bg_glass_65_ffffff_1x400.png",
    "app/assets/images/ants_admin/jquery_ui/ui-bg_gloss-wave_35_f6a828_500x100.png",
    "app/assets/images/ants_admin/jquery_ui/ui-bg_highlight-soft_100_eeeeee_1x100.png",
    "app/assets/images/ants_admin/jquery_ui/ui-bg_highlight-soft_75_ffe45c_1x100.png",
    "app/assets/images/ants_admin/jquery_ui/ui-icons_222222_256x240.png",
    "app/assets/images/ants_admin/jquery_ui/ui-icons_228ef1_256x240.png",
    "app/assets/images/ants_admin/jquery_ui/ui-icons_ef8c08_256x240.png",
    "app/assets/images/ants_admin/jquery_ui/ui-icons_ffd27a_256x240.png",
    "app/assets/images/ants_admin/jquery_ui/ui-icons_ffffff_256x240.png",
    "app/assets/javascript/.DS_Store",
    "app/assets/javascript/ants_admin/application.js",
    "app/assets/javascript/ants_admin/base.js",
    "app/assets/javascript/ants_admin/bpopup.js",
    "app/assets/javascript/ants_admin/jquery-ui-1.10.4.js",
    "app/assets/stylesheets/.DS_Store",
    "app/assets/stylesheets/ants_admin/.DS_Store",
    "app/assets/stylesheets/ants_admin/application.css",
    "app/assets/stylesheets/ants_admin/base.scss",
    "app/assets/stylesheets/ants_admin/jquery-ui-1.10.4.css",
    "app/assets/stylesheets/ants_admin/reset.css",
    "app/controllers/ants_admin_controller.rb",
    "app/views/.DS_Store",
    "app/views/ants_admin/.DS_Store",
    "app/views/ants_admin/index.html.erb",
    "app/views/layouts/ants_admin.html.erb",
    "config/routes.rb",
    "lib/ants_admin.rb"
  ]
  s.homepage = "https://github.com/ThanhKhoaIT/ants_admin"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Admin panel for you"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
    else
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
  end
end

