# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ants_admin 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "ants_admin"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["KarlNguyen"]
  s.date = "2014-11-18"
  s.description = "Admin panel for you"
  s.email = "thanhkhoait@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".DS_Store",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "ants_admin.gemspec",
    "app/assets/images/ants_admin/ajax-loader1.gif",
    "app/assets/images/ants_admin/avatar.png",
    "app/assets/images/ants_admin/blur-background09.jpg",
    "app/assets/images/ants_admin/fonts/FontAwesome.otf",
    "app/assets/images/ants_admin/fonts/M2Jd71oPJhLKp0zdtTvoM_bce-VcyLJMRR1FC9qWbU8.woff",
    "app/assets/images/ants_admin/fonts/ODelI1aHBYDBqgeIAH2zlNHq-FFgoDNV3GTKpHwuvtI.woff",
    "app/assets/images/ants_admin/fonts/fontawesome-webfont.eot",
    "app/assets/images/ants_admin/fonts/fontawesome-webfont.svg",
    "app/assets/images/ants_admin/fonts/fontawesome-webfont.ttf",
    "app/assets/images/ants_admin/fonts/fontawesome-webfont.woff",
    "app/assets/images/ants_admin/fonts/fpTVHK8qsXbIeTHTrnQH6H7XMO6S-yJpg1torQFmnv33rGVtsTkPsbDajuO5ueQw.woff",
    "app/assets/images/ants_admin/fonts/fpTVHK8qsXbIeTHTrnQH6J4LxuTxC3JbLqy8IUt0K1T3rGVtsTkPsbDajuO5ueQw.woff",
    "app/assets/images/ants_admin/fonts/glyphicons-halflings-regular.eot",
    "app/assets/images/ants_admin/fonts/glyphicons-halflings-regular.svg",
    "app/assets/images/ants_admin/fonts/glyphicons-halflings-regular.ttf",
    "app/assets/images/ants_admin/fonts/glyphicons-halflings-regular.woff",
    "app/assets/images/ants_admin/fonts/ionicons.eot",
    "app/assets/images/ants_admin/fonts/ionicons.svg",
    "app/assets/images/ants_admin/fonts/ionicons.ttf",
    "app/assets/images/ants_admin/fonts/ionicons.woff",
    "app/assets/images/ants_admin/fonts/qx1LSqts-NtiKcLw4N03ILDH3ri20rYH10B2w3wbVeU.woff",
    "app/assets/images/ants_admin/fonts/toadOcfmlt9b38dHJxOBGCmgpmuQqK2I-L2S9cF65Ek.woff",
    "app/assets/images/ants_admin/fonts/toadOcfmlt9b38dHJxOBGIqjGYJUyOXcBwUQbRaNH6c.woff",
    "app/assets/images/ants_admin/fonts/toadOcfmlt9b38dHJxOBGMVNtom4QlEDNJaqqqzqdSs.woff",
    "app/assets/images/ants_admin/jquery_ui/animated-overlay.gif",
    "app/assets/images/ants_admin/jquery_ui/ui-bg_diagonals-thick_18_b81900_40x40.png",
    "app/assets/images/ants_admin/jquery_ui/ui-bg_diagonals-thick_20_666666_40x40.png",
    "app/assets/images/ants_admin/jquery_ui/ui-bg_flat_10_000000_40x100.png",
    "app/assets/images/ants_admin/jquery_ui/ui-bg_glass_100_f6f6f6_1x400.png",
    "app/assets/images/ants_admin/jquery_ui/ui-bg_glass_100_fdf5ce_1x400.png",
    "app/assets/images/ants_admin/jquery_ui/ui-bg_glass_65_ffffff_1x400.png",
    "app/assets/images/ants_admin/jquery_ui/ui-bg_gloss-wave_35_f6a828_500x100.png",
    "app/assets/images/ants_admin/jquery_ui/ui-bg_highlight-soft_100_eeeeee_1x100.png",
    "app/assets/images/ants_admin/jquery_ui/ui-bg_highlight-soft_75_ffe45c_1x100.png",
    "app/assets/images/ants_admin/jquery_ui/ui-icons_222222_256x240.png",
    "app/assets/images/ants_admin/jquery_ui/ui-icons_228ef1_256x240.png",
    "app/assets/images/ants_admin/jquery_ui/ui-icons_ef8c08_256x240.png",
    "app/assets/images/ants_admin/jquery_ui/ui-icons_ffd27a_256x240.png",
    "app/assets/images/ants_admin/jquery_ui/ui-icons_ffffff_256x240.png",
    "app/assets/images/ants_admin/minimal.png",
    "app/assets/images/ants_admin/minimal@2x.png",
    "app/assets/javascript/ants_admin/application.js",
    "app/assets/javascript/ants_admin/base.js",
    "app/assets/javascript/ants_admin/bpopup.js",
    "app/assets/javascript/ants_admin/jquery-ui-1.10.4.js",
    "app/assets/javascript/ants_admin/lte/app.js",
    "app/assets/javascript/ants_admin/lte/bootstrap.js",
    "app/assets/javascript/ants_admin/lte/dashboard.js",
    "app/assets/javascript/ants_admin/lte/plugins/bootstrap-slider/bootstrap-slider.js",
    "app/assets/javascript/ants_admin/lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js",
    "app/assets/javascript/ants_admin/lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.js",
    "app/assets/javascript/ants_admin/lte/plugins/colorpicker/bootstrap-colorpicker.js",
    "app/assets/javascript/ants_admin/lte/plugins/datatables/1.jquery.dataTables.js",
    "app/assets/javascript/ants_admin/lte/plugins/datatables/2.dataTables.bootstrap.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/bootstrap-datepicker.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.ar.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.az.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.bg.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.ca.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.cs.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.cy.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.da.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.de.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.el.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.es.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.et.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.fa.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.fi.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.fr.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.gl.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.he.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.hr.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.hu.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.id.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.is.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.it.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.ja.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.ka.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.kk.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.kr.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.lt.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.lv.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.mk.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.ms.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.nb.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.nl-BE.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.nl.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.no.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.pl.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.pt-BR.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.pt.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.ro.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.rs-latin.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.rs.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.ru.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.sk.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.sl.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.sq.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.sv.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.sw.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.th.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.tr.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.ua.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.vi.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.zh-CN.js",
    "app/assets/javascript/ants_admin/lte/plugins/datepicker/locales/bootstrap-datepicker.zh-TW.js",
    "app/assets/javascript/ants_admin/lte/plugins/daterangepicker/daterangepicker.js",
    "app/assets/javascript/ants_admin/lte/plugins/flot/1.jquery.flot.js",
    "app/assets/javascript/ants_admin/lte/plugins/flot/excanvas.js",
    "app/assets/javascript/ants_admin/lte/plugins/flot/jquery.colorhelpers.js",
    "app/assets/javascript/ants_admin/lte/plugins/flot/jquery.flot.canvas.js",
    "app/assets/javascript/ants_admin/lte/plugins/flot/jquery.flot.categories.js",
    "app/assets/javascript/ants_admin/lte/plugins/flot/jquery.flot.crosshair.js",
    "app/assets/javascript/ants_admin/lte/plugins/flot/jquery.flot.errorbars.js",
    "app/assets/javascript/ants_admin/lte/plugins/flot/jquery.flot.fillbetween.js",
    "app/assets/javascript/ants_admin/lte/plugins/flot/jquery.flot.image.js",
    "app/assets/javascript/ants_admin/lte/plugins/flot/jquery.flot.navigate.js",
    "app/assets/javascript/ants_admin/lte/plugins/flot/jquery.flot.pie.js",
    "app/assets/javascript/ants_admin/lte/plugins/flot/jquery.flot.resize.js",
    "app/assets/javascript/ants_admin/lte/plugins/flot/jquery.flot.selection.js",
    "app/assets/javascript/ants_admin/lte/plugins/flot/jquery.flot.stack.js",
    "app/assets/javascript/ants_admin/lte/plugins/flot/jquery.flot.symbol.js",
    "app/assets/javascript/ants_admin/lte/plugins/flot/jquery.flot.threshold.js",
    "app/assets/javascript/ants_admin/lte/plugins/flot/jquery.flot.time.js",
    "app/assets/javascript/ants_admin/lte/plugins/iCheck/icheck.js",
    "app/assets/javascript/ants_admin/lte/plugins/input-mask/1.jquery.inputmask.js",
    "app/assets/javascript/ants_admin/lte/plugins/input-mask/jquery.inputmask.date.extensions.js",
    "app/assets/javascript/ants_admin/lte/plugins/input-mask/jquery.inputmask.extensions.js",
    "app/assets/javascript/ants_admin/lte/plugins/input-mask/jquery.inputmask.numeric.extensions.js",
    "app/assets/javascript/ants_admin/lte/plugins/input-mask/jquery.inputmask.phone.extensions.js",
    "app/assets/javascript/ants_admin/lte/plugins/input-mask/jquery.inputmask.regex.extensions.js",
    "app/assets/javascript/ants_admin/lte/plugins/input-mask/phone-codes/phone-be.json",
    "app/assets/javascript/ants_admin/lte/plugins/input-mask/phone-codes/phone-codes.json",
    "app/assets/javascript/ants_admin/lte/plugins/input-mask/phone-codes/readme.txt",
    "app/assets/javascript/ants_admin/lte/plugins/ionslider/ion.rangeSlider.min.js",
    "app/assets/javascript/ants_admin/lte/plugins/jqueryKnob/jquery.knob.js",
    "app/assets/javascript/ants_admin/lte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js",
    "app/assets/javascript/ants_admin/lte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js",
    "app/assets/javascript/ants_admin/lte/plugins/misc/html5shiv.js",
    "app/assets/javascript/ants_admin/lte/plugins/misc/jquery.ba-resize.min.js",
    "app/assets/javascript/ants_admin/lte/plugins/misc/jquery.placeholder.js",
    "app/assets/javascript/ants_admin/lte/plugins/misc/modernizr.min.js",
    "app/assets/javascript/ants_admin/lte/plugins/misc/respond.min.js",
    "app/assets/javascript/ants_admin/lte/plugins/morris/1.raphael-min.js",
    "app/assets/javascript/ants_admin/lte/plugins/morris/morris.js",
    "app/assets/javascript/ants_admin/lte/plugins/slimScroll/jquery.slimscroll.js",
    "app/assets/javascript/ants_admin/lte/plugins/slimScroll/slimScroll.jquery.json",
    "app/assets/javascript/ants_admin/lte/plugins/sparkline/jquery.sparkline.js",
    "app/assets/javascript/ants_admin/lte/plugins/timepicker/bootstrap-timepicker.js",
    "app/assets/javascript/ants_admin/vendors/jquery.dynatable.js",
    "app/assets/javascript/ants_admin/vendors/jquery.popup.js",
    "app/assets/javascript/ants_admin/vendors/queue.js",
    "app/assets/stylesheets/.DS_Store",
    "app/assets/stylesheets/ants_admin/.DS_Store",
    "app/assets/stylesheets/ants_admin/admin_lte.scss",
    "app/assets/stylesheets/ants_admin/application.css",
    "app/assets/stylesheets/ants_admin/base.scss",
    "app/assets/stylesheets/ants_admin/blur.svg",
    "app/assets/stylesheets/ants_admin/reset.css",
    "app/assets/stylesheets/ants_admin/styles.scss",
    "app/assets/stylesheets/ants_admin/vendors/bootstrap-timepicker.css",
    "app/assets/stylesheets/ants_admin/vendors/bootstrap.min.css",
    "app/assets/stylesheets/ants_admin/vendors/bootstrap3-wysihtml5.min.css",
    "app/assets/stylesheets/ants_admin/vendors/datepicker3.css",
    "app/assets/stylesheets/ants_admin/vendors/daterangepicker-bs3.css",
    "app/assets/stylesheets/ants_admin/vendors/font-awesome.min.css",
    "app/assets/stylesheets/ants_admin/vendors/ionicons.min.css",
    "app/assets/stylesheets/ants_admin/vendors/jquery-jvectormap-1.2.2.css",
    "app/assets/stylesheets/ants_admin/vendors/jquery-ui-1.10.4.css",
    "app/assets/stylesheets/ants_admin/vendors/jquery.dynatable.css",
    "app/assets/stylesheets/ants_admin/vendors/jquery.popup.scss",
    "app/assets/stylesheets/ants_admin/vendors/morris.css",
    "app/controllers/ants_admin/admins_controller.rb",
    "app/controllers/ants_admin_controller.rb",
    "app/helpers/ants_admin/form_helper.rb",
    "app/helpers/ants_admin/input_helper.rb",
    "app/helpers/ants_admin/menu_helper.rb",
    "app/helpers/ants_admin/page_helper.rb",
    "app/mailers/ants_admin/mailer.rb",
    "app/views/.DS_Store",
    "app/views/ants_admin/.DS_Store",
    "app/views/ants_admin/_form.html.erb",
    "app/views/ants_admin/dashboard.html.erb",
    "app/views/ants_admin/edit.html.erb",
    "app/views/ants_admin/index.html.erb",
    "app/views/ants_admin/mailer/confirmation_instructions.html.erb",
    "app/views/ants_admin/mailer/reset_password_instructions.html.erb",
    "app/views/ants_admin/mailer/unlock_instructions.html.erb",
    "app/views/ants_admin/new.html.erb",
    "app/views/ants_admin/unlocks/new.html.erb",
    "app/views/layouts/ants_admin.html.erb",
    "app/views/layouts/ants_admin_login.html.erb",
    "app/views/layouts/areas/_account_info.html.erb",
    "app/views/layouts/areas/_header.html.erb",
    "app/views/layouts/areas/_main_menu.html.erb",
    "app/views/layouts/areas/_search_box.html.erb",
    "config/routes.rb",
    "lib/ants_admin.rb",
    "lib/ants_admin/smart_model.rb",
    "lib/generators/active_record/ants_admin_generator.rb",
    "lib/generators/active_record/templates/migration.rb",
    "lib/generators/active_record/templates/migration_existing.rb",
    "lib/generators/ants_admin/ants_admin_generator.rb",
    "lib/generators/ants_admin/install_generator.rb",
    "lib/generators/ants_admin/orm_helpers.rb",
    "lib/generators/templates/ants_admin.rb"
  ]
  s.homepage = "https://github.com/ThanhKhoaIT/ants_admin"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Admin panel for you"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<orm_adapter>, ["~> 0.5.0"])
      s.add_runtime_dependency(%q<formtastic>, ["~> 3.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<orm_adapter>, ["~> 0.5.0"])
      s.add_dependency(%q<formtastic>, ["~> 3.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<orm_adapter>, ["~> 0.5.0"])
    s.add_dependency(%q<formtastic>, ["~> 3.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

